import Head from "next/head";
import Login from "@/components/login";
export default function Home() {
  return (
    <div className="dark text-black dark:text-white">
      <Head>
        <title>cherry blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Login />
      </main>
    </div>
  );
}
